spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dotodo?createDatabaseIfNotExist=true
    username: root
    password: vikas1234
    driver-class-name: org.postgresql.Driver